language: python
if: tag IS present
cache: pip
env:
  global:
    secure: VZOHb2OeqHMjeHhIMN9+9xN5lOU52kvoDtTRFXyOafkZaASOWlkvMBMCShckx4Wi2dChGjCNHe0P/MKWthDvM3RzHT3dzUjYe+K0PBEdPKNv5YX1xkLH03ObmFnjyu/hSvz9LJBzjbV2EkLD50tEk18o1Ix3ekjePbwHpMqenYu+7lph7VUTIy71ClNQXQ8/uIFfSuQ7Blu9FLMQh2mPkZYzQphT1gIQ8D1vof2jLQLu5uIOedmWQWQOms0o0Alw81ts2Ndh+ftxlXeNucqtZaQdxRbfEXhX3X0nJZnE1afGNc+tXb3t4O3RwztWKTZBpwYYsW9O3f4KMh5+JXwNEKBV9T7/IETQCiPKB2VVI7Jvgv5/rWoZYqYU8HuBilaJcQZ0sYt9VL0f2WHve54sZ/V6eWJWplFgaf4yF1RwlisqsxDu2JyQnLSH4ct+3MUFupduc/T5SDQBMsy53Bpk8DVQ/EfdUCjmUWiIG7PvBw60YCjxoXxhHZuKZl6ervG1UBuHV6uRpL4NVh2QIQhrt/p8RQe3slN9R2A8RjsT1GdO85l66HAn/ijnacFjhN+9AW5lyItH0yLCRO447bUZ3ir73lhHi1nj2VRi1yJyb74r7TsF1/veEGP44Jqi+rd1MXkdiTIhladhlp3DVYe6BC5O1+m7sNdOlHNJMjGHkjA=
  api_key:
    secure: bYLxJCpemvCu6AKeILZ1qwAFAOZnsLjchquB6G+wCAwlZ+sGM+/zZVT9YFQXZGGxaw683iaWq/z+SCxHvnkuZDs0Fjqqxy6dFu17I0Ri2tSwRSpWIKAkX7JxcjQFIMcTZBA40TvumB7X1r8XaxQXVZ3iPzgkVdbtlRJCC1f9VNmKG4OTdysGvC+YeyGI1OT5D8oZkmFpcZ2aOlWfkTSQw8d6XdiEt00seZibzmK4mx7dmiuwX/zyqKPlEnDZ0T4ZlSSeGh2GBJ9IVZC+7CvTv6cpPmUpSHugTdj7bkIUEht1H1w0O7oOmRGpKcPLloTkVsaP0+TpgSUfwbxURs/n51gdmLpjdGJVOWua5zKqXjoR9v2HVovOt+DhrGCYgmt8lsOAIvAhD8D9Ihf4/UN7YQ5NQleHXXbS6mXIDvJQqXsHu/+qvSSKFyoi9gb2ief8dJlsLcPLYP44QXo+ZURzNTnvOw7fbzida7wtsepSztlX59PzmU/nukneddOZQdgk/mpHqX41sOkdylAyPtMjjQ0IxWDRMI2mC0ev3Ql6wa2Jabv6GWSuzSdQ4DLM7H8iINgvPrnqxmRA4Kz7x/jJrPFuE9HvE33kRYGNZRO6ukh06fOmHPQSoLaH1IJ5BDPccIf1rS0aNFBXEPXjpGCaMcv1w1zGsjftqZvt0Ak8cO4=
install:
- pip install -r requirements.txt
script:
- git clean -f -d -x
after_success:
- ". ./.ci/deploy.sh"
- eval $(ssh-agent -s)
- openssl aes-256-cbc -K $encrypted_5c4519557e13_key -iv $encrypted_5c4519557e13_iv
  -in app-dev-workshop-deploy-key.enc -d | ssh-add -
- git config user.name "$GH_USER_NAME"
- git config user.email "$GH_USER_EMAIL"
- git remote set-url origin git@github.com:signalfx/app-dev-workshop.git
deploy:
  provider: script
  script: |
    RESULT=$(curl -s -w "\n%{http_code}\n" \
      "https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases" \
      -H "Authorization: token $api_token"  \
      -d @- <<'EOF'
    {
      "tag_name":         "$TRAVIS_TAG"
    }
    EOF
    )
    if [ "$(tail -1 <<< $RESULT)" != "201" ]; then
      echo FAILED
      echo "$RESULT"
      exit 1
    fi
    RELEASE_ID=$(sed -ne 's/^  "id": \(.*\),$/\1/p' <<< $RESULT)
    if [[ -z "$RELEASE_ID" ]]; then
      echo FAILED
      echo "$RESULT"
      exit 1
    fi
  on:
    repo: signalfx/app-dev-workshop
    tags: true
after_deploy:
- git remote set-branches --add origin gh-pages
- git fetch origin && git fetch origin gh-pages:gh-pages;
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    echo "Pushing to github";
    mkdocs gh-deploy -v --clean -m "$MSG" --remote-name origin
    git push origin gh-pages;
  fi
