#cloud-config
package_update: true
package_upgrade: true

packages:
 - apache2-utils

runcmd:
 - snap install microk8s --classic
 - 'git clone https://github.com/signalfx/streaming-analytics-workshop.git /home/ubuntu/workshop'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/etc/motd -o /etc/motd'
 - chown -R ubuntu:ubuntu /home/ubuntu/workshop 
 - echo '--containerd=${SNAP_COMMON}/run/containerd.sock' >> /var/snap/microk8s/current/args/kubelet
 - usermod -a -G microk8s ubuntu
 - 'curl -OL https://github.com/derailed/k9s/releases/download/v0.16.1/k9s_Linux_x86_64.tar.gz'
 - tar xvfz k9s_Linux_x86_64.tar.gz
 - mv k9s /usr/local/bin
