#cloud-config
package_update: true
package_upgrade: true

write_files:
 - content: |
      [Unit]
      Description=SignalFx Smart Gateway
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/smart-gateway --configfile /var/lib/gateway/etc/gateway.conf
      KillMode=mixed
      Restart=on-failure
      Type=simple
      User=root
      Group=root

      [Install]
      WantedBy=multi-user.target
   path: /lib/systemd/system/smart-gateway.service
   permissons: '0644'

runcmd:
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/etc/motd -o /etc/motd'
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/smart-gateway/install.sh -o /home/ubuntu/smartgateway-install.sh'
 - chown ubuntu:ubuntu /home/ubuntu/smartgateway-install.sh
 - chmod 755 /home/ubuntu/smartgateway-install.sh
 # Replace ACCESS_TOKEN, REALM, HOSTNAME & CLUSTER_NAME accordingly
 - ./home/ubuntu/smartgateway-install.sh ACCESS_TOKEN REALM HOSTNAME CLUSTER_NAME
 - systemctl enable smart-gateway.service
 - systemctl daemon-reload
 - systemctl restart smart-gateway
