#cloud-config
package_update: true
package_upgrade: true

packages:
 - apache2-utils

runcmd:
 - snap install microk8s --classic --channel=1.16/stable
 - mkdir /home/ubuntu/signalfx-agent
 - mkdir /home/ubuntu/nginx
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/signalfx-agent/clusterrole.yaml -o /home/ubuntu/signalfx-agent/clusterrole.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/signalfx-agent/clusterrolebinding.yaml -o /home/ubuntu/signalfx-agent/clusterrolebinding.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/microk8s/configmap.yaml -o /home/ubuntu/signalfx-agent/configmap.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/signalfx-agent/daemonset.yaml -o /home/ubuntu/signalfx-agent/daemonset.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/signalfx-agent/serviceaccount.yaml -o /home/ubuntu/signalfx-agent/serviceaccount.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/nginx/nginx-deployment.yaml -o /home/ubuntu/nginx/nginx-deployment.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k8s/nginx/nginx.conf -o /home/ubuntu/nginx/nginx.conf'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/etc/motd -o /etc/motd'
 - chown -R ubuntu:ubuntu /home/ubuntu/signalfx-agent
 - chown -R ubuntu:ubuntu /home/ubuntu/nginx
 - echo '--containerd=${SNAP_COMMON}/run/containerd.sock' >> /var/snap/microk8s/current/args/kubelet 
