#cloud-config
package_update: true
package_upgrade: true
runcmd:
 - apt install apt-transport-https ca-certificates gnupg-agent software-properties-common -y 
 - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
 - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
 - apt update
 - apt install docker-ce docker-ce-cli containerd.io -y
 - 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --docker" sh -s -'
