#cloud-config
package_update: true
package_upgrade: true

packages:
 - apache2-utils

runcmd:
 - snap install microk8s --classic
 - 'git clone https://github.com/signalfx/streaming-analytics-workshop.git /home/ubuntu/workshop'
 - mkdir /home/ubuntu/signalfx-agent
 - mkdir /home/ubuntu/nginx
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/signalfx-agent/clusterrole.yaml -o /home/ubuntu/signalfx-agent/clusterrole.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/signalfx-agent/clusterrolebinding.yaml -o /home/ubuntu/signalfx-agent/clusterrolebinding.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/microk8s/configmap.yaml -o /home/ubuntu/signalfx-agent/configmap.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/signalfx-agent/daemonset.yaml -o /home/ubuntu/signalfx-agent/daemonset.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/signalfx-agent/serviceaccount.yaml -o /home/ubuntu/signalfx-agent/serviceaccount.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/nginx/nginx-deployment.yaml -o /home/ubuntu/nginx/nginx-deployment.yaml'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/k3s/nginx/nginx.conf -o /home/ubuntu/nginx/nginx.conf'
 - 'curl https://raw.githubusercontent.com/signalfx/streaming-analytics-workshop/master/etc/motd -o /etc/motd'
 - chown -R ubuntu:ubuntu /home/ubuntu/signalfx-agent
 - chown -R ubuntu:ubuntu /home/ubuntu/nginx
 - chown -R ubuntu:ubuntu /home/ubuntu/workshop 
 - echo '--containerd=${SNAP_COMMON}/run/containerd.sock' >> /var/snap/microk8s/current/args/kubelet
 - usermod -a -G microk8s ubuntu
 - 'curl -OL https://github.com/derailed/k9s/releases/download/v0.13.6/k9s_0.13.6_Linux_x86_64.tar.gz'
 - tar xvfz k9s_0.13.6_Linux_x86_64.tar.gz
 - mv k9s /usr/local/bin
