#cloud-config
package_update: true
package_upgrade: true
packages:
 - default-jre            
 - openjdk-11-jre-headless
 - openjdk-8-jre-headless
 - maven
 - python3-distutils
 - apache2-utils
write_files:
 - content: |
      "Hello from the SAW Workshop!"
   path: /home/ubuntu/mypythonapp/post_data.json
   permissons: '0644'
 - content: | 
      #!/usr/bin/env python
 
      from flask import Flask, make_response, request
      from signalfx_tracing import trace
      import opentracing
 
      app = Flask(__name__)
    
      @trace
      def convert_response(message):
        # In this example we want to force this trace to be retained
        opentracing.tracer.active_span.set_tag('sampling.priority', 1)
        opentracing.tracer.active_span.set_tag('message', message)
        print(opentracing.tracer.active_span)
        return 'You said: {}'.format(message)
 
      @app.route('/echo', methods=['POST'])
      def echo():
        message = request.data.decode('utf-8')
        return make_response(convert_response(message))
 
      if __name__ == '__main__':
        app.run()

   path: /home/ubuntu/mypythonapp/demo.py
   permissions: '0755'
runcmd:
 - "curl -L https://github.com/signalfx/streaming-analytics-workshop/raw/master/apm/java-app.tar.gz -o /run/java-app.tar.gz"
 - tar xvfz /run/java-app.tar.gz -C /home/ubuntu/
 - chown -R ubuntu:ubuntu /home/ubuntu
 - "curl https://bootstrap.pypa.io/get-pip.py -o /run/get-pip.py"
 - python3 /run/get-pip.py
 - pip install flask requests signalfx-tracing
 - sfx-py-trace-bootstrap