site_name: 'Splunk App Dev Workshop'
site_description: 'This workshop is going to take you through the exciting journey of App Dev, what this is, why this is important, and how to get started right away!'
site_author: 'Sales Engineering'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
#repo_url: 'https://github.com/signalfx/app-dev-workshop/'
#edit_uri: 'edit/master/docs/'
copyright: Copyright &copy; 2020 Splunk Inc. All rights reserved.
remote_branch: gh-pages

versions:
  - v1.3
  - v1.2

theme:
  name: material
  palette:
    primary: 'black'
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: docs/material
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite


extra_css:
  - "extra.css"

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: en
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        
nav:
  - '<b>Home</b>': index.md
  - '<b>Introduction</b>': introduction.md
  - '<b>Module 1</b> - Dashboards':
    - 'Introduction': module1/intro.md
    - 'Editing Charts': module1/editing.md
    - 'Using filters': module1/filtering.md
    - 'Using formulas': module1/formulas.md
    - 'Using overlays': module1/overlay.md
    - 'Introduction to SignalFlow': module1/signalflow.md
    - 'Adding charts to dashboards': module1/adding-charts.md
  - '<b>Module 2</b> - Detectors':
    - 'Working with Detectors': module2/detectors.md
    - 'Working with Muting Rules': module2/muting.md
  - '<b>Module 3</b> - Smart Agent':
    - 'Preparation': module3/prep.md
    - 'Deploying the Smart Agent in Kubernetes (K3s)': module3/k3s.md
    - 'Deploying NGINX in K3s' : module3/nginx.md
  - '<b>Module 4</b> - Monitoring as Code':
    - 'Using Terraform for charts and dashboards' : module4/terraform.md
  - '<b>Module 5</b> - Service Bureau':
    - 'Billing and Usage' : module5/service_bureau.md
    - 'Teams' : module5/teams.md
  - '<b>Module 6</b> - µAPM':
    - 'µAPM Architecture Overview': module6/index.md
    - 'Deploying Hot R.O.D. in K3s': module6/hotrod.md
    - 'Deploying Sock Shop in K3s': module6/sockshop.md
  - '<b>Module 7</b> - VictorOps':
    - 'VictorOps Getting Started': module7/vo_getting_started.md
    - 'VictorOps Integrations': module7/vo_integrations.md
    - 'VictorOps Incident Lifecycle': module7/vo_incident_lifecycle.md
  - '<b>Post Workshop Clean Up!</b>': module-support/cleanup.md
  - '<b>Optional Modules</b>':
    - 'Deploying Hot R.O.D. in EKS': module8/hotrod-eks.md
    - 'Creating an AWS/EC2 instance': module-support/ec2-setup.md
    - 'Deploying the Smart Agent on a VM': module-support/vm.md
