#cloud-config
ssh_pwauth: yes
password: Observability2020!
chpasswd:
  expire: false

package_update: true

packages:
  - unzip

runcmd:
# Download Workshop
- export WSVERSION=1.24
- 'export WSARCHIVE=$([ "$WSVERSION" = "master" ] && echo "master" || echo "v$WSVERSION")'
- curl -s -OL https://github.com/signalfx/observability-workshop/archive/$WSARCHIVE.zip
- unzip -qq $WSARCHIVE.zip -d /home/ubuntu/
- mv /home/ubuntu/observability-workshop-$WSVERSION /home/ubuntu/workshop
# Configure motd
- curl -s https://raw.githubusercontent.com/signalfx/observability-workshop/master/etc/motd -o /etc/motd
- chmod -x /etc/update-motd.d/*
# Install Terraform
- curl -s -OL https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
- unzip -qq terraform_0.12.25_linux_amd64.zip -d /usr/local/bin/
# Set correct permissions on ubuntu user home directory
- chown -R ubuntu:ubuntu /home/ubuntu
