site_name: 'App Dev Workshop'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
repo_url: 'https://github.com/signalfx/app-dev-workshop/'
remote_branch: gh-pages
theme:
  name: material
  #custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true
  favicon: 'images/favicon.ico'
  logo: 'images/logo.png'

markdown_extensions:
  - admonition

extra_css:
  - "extra.css"

nav:
  - Overview: index.md
  - 'Module One':
    - '1. Working with Dashboards, Charts and Metrics': module1/dashboards.md
    - '2. Working with Detectors': module1/detectors.md
    - '3. Working with Muting Rules': module1/muting.md
    - '4. Running the Smart Agent in Kubernetes (K3s)': module1/k3s.md
    - '5. Deploying NGINX in K3s': module1/nginx.md
    - '6. Monitoring as Code with Detectors & Dashboards': module1/terraform.md
  - 'Module Two':
    - '1. µAPM: Hotrod in K3s': module2/hotrod.md
