site_name: 'App Dev Workshop'
site_description: 'Splunk App Dev Workshop'
site_author: 'Sales Engineering'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
repo_url: 'https://github.com/signalfx/app-dev-workshop/'
edit_uri: 'edit/master/docs/modules/'
copyright: Copyright &copy; 2020 Splunk Inc. All rights reserved.
remote_branch: gh-pages
docs_dir: modules
theme:
  name: material
  palette:
    primary: 'black'
  favicon: 'images/favicon.ico'
  logo: 'images/logo.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

extra_css:
  - "extra.css"

plugins:
  - git-revision-date-localized
  
nav:
  - Overview: index.md
  - '<b>Module 1</b> - Dashboards':
    - 'Working with Dashboards, Charts and Metrics': module1/dashboards.md
  - '<b>Module 2</b> - Detectors':
    - 'Working with Detectors': module2/detectors.md
    - 'Working with Muting Rules': module2/muting.md
  - '<b>Module 3</b> - Smart Agent':
    - 'Deploying the Smart Agent in Kubernetes (K3s)': module3/k3s.md
    - 'Deploying NGINX in K3s' : module3/nginx.md
  - '<b>Module 4</b> - Monitoring as Code':
    - 'Using Terraform for charts and dashboards' : module4/terraform.md
  - '<b>Module 5</b> - Service Bureau':
    - 'Billing and Usage' : module5/service_bureau.md
    - 'Teams' : module5/teams.md
  - '<b>Module 6</b> - µAPM':
    - 'Running Hotrod in K3s': module6/hotrod.md
    - 'Running Sock Shop in K3s': module6/sockshop.md
  - '<b>Module 7</b> - VictorOps':
    - 'Coming Soon!': module7/index.md
  - 'Post Workshop Clean Up!': cleanup.md
