site_name: 'App Dev Workshop'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
repo_url: 'https://github.com/signalfx/app-dev-workshop/'
remote_branch: gh-pages
theme:
  name: 'material'
  language: 'en'
  favicon: 'images/favicon.ico'
  logo: 'images/logo.png'
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'

markdown_extensions:
  # Code highlighting in ``` ``` blocks
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs

nav:
  - Overview: index.md
  - 'Module One':
    - '1. Working with Dashboards, Charts and Metrics': module1/dashboards.md
  - 'Module Two':
    - '1. µAPM: Hotrod in K3s': module2/hotrod.md
extra_css:
  - extra.css

plugins:
  - search
  - git-revision-date-localized